// -----------------------------------------------------------------------------
// Ogham — a dual-voice bytebeat synthesizer for Eurorack
//
// Author:     Steven Collins, 2026, Keeos.io
// Copyright:  (c) 2026 Steven Collins
//
// SPDX-FileCopyrightText: 2026 Steven Collins <https://keeos.io>
// SPDX-License-Identifier: MIT
//
// This file is part of the Ogham firmware. See LICENSE-firmware.txt at the
// repository root for the full licence text.
// https://github.com/keeos-io/ogham
// -----------------------------------------------------------------------------

#pragma once
#include <cstdint>

// ByteBeat formula function signature
// All formulas take t (time), a (parameter A), b (parameter B)
// and return an 8-bit audio sample
typedef uint8_t (*BytebeatFormula)(uint32_t t, int32_t a, int32_t b);

// Formula metadata
struct FormulaInfo {
    const char* name;
    const char* author;
    BytebeatFormula func;
    int baseSampleRate;     // 8000, 11025, 16000, 32000, or 44100
};

// --- JS-compatible shift helpers ---
// Mask shift amount to 0-31 to match JavaScript semantics

inline int32_t shr(int32_t val, int32_t shift) {
    return val >> (shift & 31);
}

// Shifting a negative value left is undefined before C++20, and this does it
// constantly by design: JavaScript's << is defined on a wrapped int32, and
// reproducing that is the entire purpose of these helpers. Going through
// uint32_t and back is the well-defined spelling of the same operation, but it
// compiles to a different binary — not a free swap on a synth whose formulas
// are the sound.
inline int32_t shl(int32_t val, int32_t shift) {
    // cppcheck-suppress shiftNegativeLHS
    return val << (shift & 31);
}

// Safe division (avoid div-by-zero, match JS truncation)
inline int32_t safediv(int32_t num, int32_t den) {
    if (den == 0) return 0;
    return num / den;
}

// Safe modulo (avoid div-by-zero)
inline int32_t safemod(int32_t num, int32_t den) {
    if (den == 0) return 0;
    return num % den;
}

// --- Compiled formula functions ---
//
// GENERATED by bytebeat/tools/gen_ogham_bank.cpp from the curated library.
// Do not hand-edit: regenerate, so the bank and the library stay the same
// set of sounds. Each function is the curated infix expression translated
// one operator at a time, fully parenthesised, with the app's evaluator
// semantics preserved (int32 throughout, shifts masked to 0-31, division
// and modulo by zero yielding zero, and only the low 8 bits reaching the
// DAC).
//
// Slots: textural 0-19, noise 20-39, percussive 40-59, rhythmic 60-79,
// melodic 80-99.

// F00: textural - Electric Drone
// Infix: (b | ~(t + b)) / a ^ a * b % (a & t + 7) * (b + t) / 16384 + t
static inline uint8_t formula_electric_drone(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safediv((b | (~(i + b))), a) ^ (safediv((safemod((a * b), (a & (i + 7))) * (b + i)), 16384) + i))) & 0xFF;
}

// F01: textural - Lofi Drone
// Infix: b / 155 + (t ^ (t / b / (56 / ((189 & b - t) % t & (a - (b | a | (b & 300) % 142 ^ t) + 41 - b & t))) ^ t) - 188) - (~2048 + t + b) % a
static inline uint8_t formula_lofi_drone(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((safediv(b, 155) + (i ^ ((safediv(safediv(i, b), safediv(56, (safemod((189 & (b - i)), i) & ((((a - ((b | a) | (safemod((b & 300), 142) ^ i))) + 41) - b) & i)))) ^ i) - 188))) - safemod((((~2048) + i) + b), a))) & 0xFF;
}

// F02: textural - Disolving Beat
// Infix: ((a ^ t) + t + (b + -~t) + (51 << 11) / (t + t) ^ -(126 + 162 ^ t) % t) >> t / (12000 + 600)
static inline uint8_t formula_disolving_beat(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(shr((((((a ^ i) + i) + (b + (-(~i)))) + safediv(shl(51, 11), (i + i))) ^ safemod((-((126 + 162) ^ i)), i)), safediv(i, (12000 + 600)))) & 0xFF;
}

// F03: textural - Sweep to Drone
// Infix: a ^ (-(t | ~(197 & -((4000 & a ^ (t | a) / (t | 99) | 112) - a))) >> 2500) - t % (t / b)
static inline uint8_t formula_sweep_to_drone(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((a ^ (shr((-(i | (~(197 & (-((((4000 & a) ^ safediv((i | a), (i | 99))) | 112) - a)))))), 2500) - safemod(i, safediv(i, b))))) & 0xFF;
}

// F04: textural - Sweep to Crunch
// Infix: (t + a % -t) % (b | 100) ^ ((t * b + b / ((t << b) % (b - a / 3000 - (11 / (t % ~((a << t + t) % 82) << b) - (a << t))) - 7)) / (t / a) | a / a)
static inline uint8_t formula_sweep_to_crunch(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safemod((i + safemod(a, (-i))), (b | 100)) ^ (safediv(((i * b) + safediv(b, (safemod(shl(i, b), ((b - safediv(a, 3000)) - (safediv(11, shl(safemod(i, (~safemod(shl(a, (i + i)), 82))), b)) - shl(a, i)))) - 7))), safediv(i, a)) | safediv(a, a)))) & 0xFF;
}

// F05: textural - Noisy Alarm
// Infix: t % b + t | t / a | ((((106 >> 12000 + a) % (((t ^ -t) - t - 79) / t & -213 | 100) ^ a >> t * b) - t / a ^ (~(b - 133) & 181 << a) % t) << 32768 + t) - 223
static inline uint8_t formula_noisy_alarm(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((((safemod(i, b) + i) | safediv(i, a)) | (shl((((safemod(shr(106, (12000 + a)), ((safediv((((i ^ (-i)) - i) - 79), i) & (-213)) | 100)) ^ shr(a, (i * b))) - safediv(i, a)) ^ safemod(((~(b - 133)) & shl(181, a)), i)), (32768 + i)) - 223))) & 0xFF;
}

// F06: textural - Rise of the Glitch
// Infix: ~((t - t << 171) % (t << t)) % t * ((t >> 167) * t - t) / 196 + 208 + (a + (b | t))
static inline uint8_t formula_rise_of_the_glitch(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((safediv((safemod((~safemod(shl((i - i), 171), shl(i, i))), i) * ((shr(i, 167) * i) - i)), 196) + 208) + (a + (b | i)))) & 0xFF;
}

// F07: textural - Robotic Drone
// Infix: t / ((t ^ b) - t) - (((((102 >> (151 | 200 * a * t) / t) + t | (t | 37)) >> (t & t) / b) + (a << t)) % (b / ((t | 101) ^ t)) | 213) / b ^ a
static inline uint8_t formula_robotic_drone(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((safediv(i, ((i ^ b) - i)) - safediv((safemod((shr(((shr(102, safediv((151 | ((200 * a) * i)), i)) + i) | (i | 37)), safediv((i & i), b)) + shl(a, i)), safediv(b, ((i | 101) ^ i))) | 213), b)) ^ a)) & 0xFF;
}

// F08: textural - Bitty Drone
// Infix: b - ((t / a + t) % (a % t) & t & t)
static inline uint8_t formula_bitty_drone(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((b - ((safemod((safediv(i, a) + i), safemod(a, i)) & i) & i))) & 0xFF;
}

// F09: textural - Texture Sequence
// Infix: ((t / (134 % a) % t | t - ((b + a ^ -t ^ 26) % (t & 1 / t) | b)) + t) % ((t + (a >> t * ((214 >> b >> t) * t)) & 47 & 70) * a | (t << a) - (a + (b ^ (a | 16000))))
static inline uint8_t formula_texture_sequence(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(safemod(((safemod(safediv(i, safemod(134, a)), i) | (i - (safemod((((b + a) ^ (-i)) ^ 26), (i & safediv(1, i))) | b))) + i), (((((i + shr(a, (i * (shr(shr(214, b), i) * i)))) & 47) & 70) * a) | (shl(i, a) - (a + (b ^ (a | 16000))))))) & 0xFF;
}

// F10: textural - Noise to Drone
// Infix: 16000 % ((a & t) - (a * b / t % b & t | (-t | (b + (t ^ t * b)) / a - 179 & 68 & a) & b) - (500 + t)) ^ t % 196
static inline uint8_t formula_noise_to_drone(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safemod(16000, (((a & i) - ((safemod(safediv((a * b), i), b) & i) | (((-i) | (((safediv((b + (i ^ (i * b))), a) - 179) & 68) & a)) & b))) - (500 + i))) ^ safemod(i, 196))) & 0xFF;
}

// F11: textural - Falling Down
// Infix: (t >> 2500 ^ t) & (1024 * b / t % t * ~~~t - 100 + b | (b << 71) % t)
static inline uint8_t formula_falling_down(uint32_t t, int32_t /*a*/, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((shr(i, 2500) ^ i) & ((((safemod(safediv((1024 * b), i), i) * (~(~(~i)))) - 100) + b) | safemod(shl(b, 71), i)))) & 0xFF;
}

// F12: textural - Power Drone
// Infix: (b | t) % 500 ^ t % -a
static inline uint8_t formula_power_drone(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safemod((b | i), 500) ^ safemod(i, (-a)))) & 0xFF;
}

// F13: textural - Run Away
// Infix: (t % (~(((t & -b >> a) / b + t) / (t % t - (t % (141 >> b) + 122) | 198 >> -(t / b) | a)) + t * (t / t) - 4096) * (-63 + 10000 * 145 | -110) + ~t ^ t) - 128
static inline uint8_t formula_run_away(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((((safemod(i, (((~safediv((safediv((i & shr((-b), a)), b) + i), (((safemod(i, i) - (safemod(i, shr(141, b)) + 122)) | shr(198, (-safediv(i, b)))) | a))) + (i * safediv(i, i))) - 4096)) * (((-63) + (10000 * 145)) | (-110))) + (~i)) ^ i) - 128)) & 0xFF;
}

// F14: textural - Slowly Rising
// Infix: (53 * ((50 >> (173 * 148 ^ t)) * t - t) % t & -193) + (t & 32000 << 102) - (((t * (t / -a) / b | 68) ^ 172) - (600 + t) + 208) & (b | t ^ t << 108)
static inline uint8_t formula_slowly_rising(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((((safemod((53 * ((shr(50, ((173 * 148) ^ i)) * i) - i)), i) & (-193)) + (i & shl(32000, 102))) - ((((safediv((i * safediv(i, (-a))), b) | 68) ^ 172) - (600 + i)) + 208)) & (b | (i ^ shl(i, 108))))) & 0xFF;
}

// F15: textural - Failing Electro Loop
// Infix: ((t ^ 2000) >> a) + ((a & t) + (136 << t % 12000 / a) - (t / b | 14))
static inline uint8_t formula_failing_electro_loop(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((shr((i ^ 2000), a) + (((a & i) + shl(136, safediv(safemod(i, 12000), a))) - (safediv(i, b) | 14)))) & 0xFF;
}

// F16: textural - Ring Descent
// Infix: t % (~((196 % ((t * t | t) ^ b / a) << 27) / b / t % ((~(t - t >> a) - 131 * a << 27) / b / t << (a & (66 | t)))) + t * (t / t) - 4096) * ((-63 & b * 129) / -110)
static inline uint8_t formula_ring_descent(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safemod(i, (((~safemod(safediv(safediv(shl(safemod(196, (((i * i) | i) ^ safediv(b, a))), 27), b), i), shl(safediv(safediv(shl(((~shr((i - i), a)) - (131 * a)), 27), b), i), (a & (66 | i))))) + (i * safediv(i, i))) - 4096)) * safediv(((-63) & (b * 129)), (-110)))) & 0xFF;
}

// F17: textural - Changing Times
// Infix: (t % t ^ a - t % 10000 + ((~t & t) + t)) + (t & t % ~b)
static inline uint8_t formula_changing_times(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((safemod(i, i) ^ ((a - safemod(i, 10000)) + (((~i) & i) + i))) + (i & safemod(i, (~b))))) & 0xFF;
}

// F18: textural - Scanner
// Infix: ((t ^ t) - (t + ((((t & t | t) - b) % t ^ a) % a ^ -(212 & b)))) % (t ^ t / (t ^ ~(130 - (~t >> a))))
static inline uint8_t formula_scanner(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(safemod(((i ^ i) - (i + (safemod((safemod((((i & i) | i) - b), i) ^ a), a) ^ (-(212 & b))))), (i ^ safediv(i, (i ^ (~(130 - shr((~i), a)))))))) & 0xFF;
}

// F19: textural - Texture from Tone
// Infix: (t ^ (t * b - ((t ^ (156 | (b ^ -(70 << 86)) * 39)) % 16384 + t) | t + t - a) >> a) - t | (b % (-(a * 114 << a) - (t & b + t + -a) | a) | (t + t) / a) / b
static inline uint8_t formula_texture_from_tone(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((((i ^ shr((((i * b) - (safemod((i ^ (156 | ((b ^ (-shl(70, 86))) * 39))), 16384) + i)) | ((i + i) - a)), a)) - i) | safediv((safemod(b, (((-shl((a * 114), a)) - (i & ((b + i) + (-a)))) | a)) | safediv((i + i), a)), b))) & 0xFF;
}

// F20: noise - Crunch Pulse
// Infix: (143 ^ ((~32768 / t & ((~(b % 151) >> t) + a << (7 >> 115) + 206) - 157 % 20) - ((a | t) - t) ^ b) ^ t) % 208
static inline uint8_t formula_crunch_pulse(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(safemod(((143 ^ (((safediv((~32768), i) & (shl((shr((~safemod(b, 151)), i) + a), (shr(7, 115) + 206)) - safemod(157, 20))) - ((a | i) - i)) ^ b)) ^ i), 208)) & 0xFF;
}

// F21: noise - Electronic Beating
// Infix: 17 - (b & t | t % ~((a - (t + t)) % ~(b * 82))) / b + (a << t)
static inline uint8_t formula_electronic_beating(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((17 - safediv(((b & i) | safemod(i, (~safemod((a - (i + i)), (~(b * 82)))))), b)) + shl(a, i))) & 0xFF;
}

// F22: noise - Fluttery
// Infix: ((t + t) * a / b + t / (b | t) | t / a) + b % ((a >> (~t & t % t)) % t >> t / 13 << t * ~t)
static inline uint8_t formula_fluttery(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((((safediv(((i + i) * a), b) + safediv(i, (b | i))) | safediv(i, a)) + safemod(b, shl(shr(safemod(shr(a, ((~i) & safemod(i, i))), i), safediv(i, 13)), (i * (~i)))))) & 0xFF;
}

// F23: noise - Circuit Bent
// Infix: 44100 ^ t % ~(111 * 50 + (t * 116 & t << (t / 6 & a + t) / -a) - b)
static inline uint8_t formula_circuit_bent(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((44100 ^ safemod(i, (~(((111 * 50) + ((i * 116) & shl(i, safediv((safediv(i, 6) & (a + i)), (-a))))) - b))))) & 0xFF;
}

// F24: noise - Where is my Filter
// Infix: ((a ^ a) + b ^ (b + (-(t - a) >> t - t % ~t)) * (a % (t - 131) & 102) & t) % 6000
static inline uint8_t formula_where_is_my_filter(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(safemod((((a ^ a) + b) ^ (((b + shr((-(i - a)), (i - safemod(i, (~i))))) * (safemod(a, (i - 131)) & 102)) & i)), 6000)) & 0xFF;
}

// F25: noise - Decent Into Chaos
// Infix: 16000 % (b - (t + ~~6000)) ^ (a - ~t) * (t - (-t % (((16000 % (162 ^ t % -~t) >> 16000 * (t << 78) >> 16384) + 52) * t) << b)) / (t / ((b / 26 | a) * 155))
static inline uint8_t formula_decent_into_chaos(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safemod(16000, (b - (i + (~(~6000))))) ^ safediv(((a - (~i)) * (i - shl(safemod((-i), ((shr(shr(safemod(16000, (162 ^ safemod(i, (-(~i))))), (16000 * shl(i, 78))), 16384) + 52) * i)), b))), safediv(i, ((safediv(b, 26) | a) * 155))))) & 0xFF;
}

// F26: noise - Pulsing static
// Infix: (((t ^ t % (t << -(t - t))) + t) / 100 % (t >> 7 ^ (112 & a) + 89) ^ 93) - t % (b * t & b) | 200 + t + ~t % a
static inline uint8_t formula_pulsing_static(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((((safemod(safediv(((i ^ safemod(i, shl(i, (-(i - i))))) + i), 100), (shr(i, 7) ^ ((112 & a) + 89))) ^ 93) - safemod(i, ((b * i) & b))) | ((200 + i) + safemod((~i), a)))) & 0xFF;
}

// F27: noise - Hunt The Wumpus
// Infix: (b >> t >> t / (2000 + b)) - (((~~t >> a & t) * b << (t >> (2000 | b)) >> t / (2000 + b)) - b)
static inline uint8_t formula_hunt_the_wumpus(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((shr(shr(b, i), safediv(i, (2000 + b))) - (shr(shl(((shr((~(~i)), a) & i) * b), shr(i, (2000 | b))), safediv(i, (2000 + b))) - b))) & 0xFF;
}

// F28: noise - Harmonic Noise Seq
// Infix: b + ((176 * (~b + (175 / t - 167) | a ^ 97 + t) >> t / (2000 + 190)) + ((a * t >> t / (179 ^ (-b + a | a ^ 2048 % t))) - 16000))
static inline uint8_t formula_harmonic_noise_seq(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((b + (shr((176 * (((~b) + (safediv(175, i) - 167)) | (a ^ (97 + i)))), safediv(i, (2000 + 190))) + (shr((a * i), safediv(i, (179 ^ (((-b) + a) | (a ^ safemod(2048, i)))))) - 16000)))) & 0xFF;
}

// F29: noise - Gritty Drone
// Infix: 400 + (t | t + ~(b * (a % t % ~-(t << a))) & 4000) - (t % (100 & a) | (t | (t + a - (101 | t * (~170 & 30) * 33) | t - b)))
static inline uint8_t formula_gritty_drone(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((400 + (i | ((i + (~(b * safemod(safemod(a, i), (~(-shl(i, a))))))) & 4000))) - (safemod(i, (100 & a)) | (i | (((i + a) - (101 | ((i * ((~170) & 30)) * 33))) | (i - b)))))) & 0xFF;
}

// F30: noise - Red Noise
// Infix: (t >> b) * (t << t / -a - t | b + t - (t | t)) | t - t % (a + (t >> (196 ^ t >> a) << t))
static inline uint8_t formula_red_noise(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((shr(i, b) * (shl(i, (safediv(i, (-a)) - i)) | ((b + i) - (i | i)))) | (i - safemod(i, (a + shl(shr(i, (196 ^ shr(i, a))), i)))))) & 0xFF;
}

// F31: noise - Evolution of Noise
// Infix: (a - t - (89 << t / (b + 189) & (45 & t) / t) ^ t) % b | t >> 1000
static inline uint8_t formula_evolution_of_noise(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safemod((((a - i) - (shl(89, safediv(i, (b + 189))) & safediv((45 & i), i))) ^ i), b) | shr(i, 1000))) & 0xFF;
}

// F32: noise - Riser Noise
// Infix: ((t * (t / -a) / b | 68) ^ 120) - (b ^ t)
static inline uint8_t formula_riser_noise(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((((safediv((i * safediv(i, (-a))), b) | 68) ^ 120) - (b ^ i))) & 0xFF;
}

// F33: noise - Fluttering Grind
// Infix: (b + (t ^ t * b)) / a
static inline uint8_t formula_fluttering_grind(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(safediv((b + (i ^ (i * b))), a)) & 0xFF;
}

// F34: noise - Frying Pan
// Infix: b + ((b + (t ^ t * b)) / a - 179) ^ t % b
static inline uint8_t formula_frying_pan(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((b + (safediv((b + (i ^ (i * b))), a) - 179)) ^ safemod(i, b))) & 0xFF;
}

// F35: noise - Destructive Riser
// Infix: (t * (t / -a) / b | 68) + (t - a)
static inline uint8_t formula_destructive_riser(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((safediv((i * safediv(i, (-a))), b) | 68) + (i - a))) & 0xFF;
}

// F36: noise - Oblivion
// Infix: (24000 ^ ~(t / 40 - (104 + (t & t)))) - 5000 / (t / a - (89 ^ t) % b)
static inline uint8_t formula_oblivion(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((24000 ^ (~(safediv(i, 40) - (104 + (i & i))))) - safediv(5000, (safediv(i, a) - safemod((89 ^ i), b))))) & 0xFF;
}

// F37: noise - Jet Phase
// Infix: 8000 / (8000 / (t / a * ((b ^ t) % b)))
static inline uint8_t formula_jet_phase(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(safediv(8000, safediv(8000, (safediv(i, a) * safemod((b ^ i), b))))) & 0xFF;
}

// F38: noise - Broken Morse
// Infix: -((98 + a * -195) * (t % (-(a % (~t - a + t) & t) | a) & t % (600 ^ b))) / t + (b | ((t | b) & 44100) % 30)
static inline uint8_t formula_broken_morse(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safediv((-((98 + (a * (-195))) * (safemod(i, ((-(safemod(a, (((~i) - a) + i)) & i)) | a)) & safemod(i, (600 ^ b))))), i) + (b | safemod(((i | b) & 44100), 30)))) & 0xFF;
}

// F39: noise - Grunge Gate
// Infix: 116 ^ ~(b ^ (t % a + 24000) % t) * ((-((3000 % t + 102) % b + a) ^ ((56 - b) / (a & t) & (t | 44100) | 2 - a)) % ((t - 32000) / t))
static inline uint8_t formula_grunge_gate(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((116 ^ ((~(b ^ safemod((safemod(i, a) + 24000), i))) * safemod(((-(safemod((safemod(3000, i) + 102), b) + a)) ^ ((safediv((56 - b), (a & i)) & (i | 44100)) | (2 - a))), safediv((i - 32000), i))))) & 0xFF;
}

// F40: percussive - Recursive Descent
// Infix: (a ^ 141 * a) % (a * b % (t ^ (t >> 70) + 32 + (186 ^ (~(32 ^ 2048) & (t % (t / 121) + (t ^ b) ^ t) >> t | a << -131 % (194 / 173)))) - t)
static inline uint8_t formula_recursive_descent(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(safemod((a ^ (141 * a)), (safemod((a * b), (i ^ ((shr(i, 70) + 32) + (186 ^ (((~(32 ^ 2048)) & shr(((safemod(i, safediv(i, 121)) + (i ^ b)) ^ i), i)) | shl(a, safemod((-131), safediv(194, 173)))))))) - i))) & 0xFF;
}

// F41: percussive - V8 Fall
// Infix: a * b % (-((114 - (t + t)) % ((137 >> t + (125 >> a | b ^ b)) / ((57 | -171) ^ a) ^ (-~((-75 ^ 209) << (t | b) << ~(42 << (b | a)) >> t) ^ a))) ^ t)
static inline uint8_t formula_v8_fall(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(safemod((a * b), ((-safemod((114 - (i + i)), (safediv(shr(137, (i + (shr(125, a) | (b ^ b)))), ((57 | (-171)) ^ a)) ^ ((-(~shr(shl(shl(((-75) ^ 209), (i | b)), (~shl(42, (b | a)))), i))) ^ a)))) ^ i))) & 0xFF;
}

// F42: percussive - Crash Breakdown
// Infix: ~((t + 109 | (t * (16 ^ a) % ((a * b | ~a - b) - 16384) / t * 79 & 191) * a * -t) / ((t ^ t) - b | 187) * t + (t - a / (((t >> 201 & a) + (106 << 91) ^ ~b) << 108))) / ~t
static inline uint8_t formula_crash_breakdown(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(safediv((~((safediv(((i + 109) | ((((safediv(safemod((i * (16 ^ a)), (((a * b) | ((~a) - b)) - 16384)), i) * 79) & 191) * a) * (-i))), (((i ^ i) - b) | 187)) * i) + (i - safediv(a, shl((((shr(i, 201) & a) + shl(106, 91)) ^ (~b)), 108))))), (~i))) & 0xFF;
}

// F43: percussive - Decent to Melody
// Infix: 9 - ((t * b + (56 & (a - (t - t)) % (t - (-48000 + t)) + t >> 130)) / (t / a) - (t & t / 1024)) + (a >> t)
static inline uint8_t formula_decent_to_melody(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((9 - (safediv(((i * b) + (56 & shr((safemod((a - (i - i)), (i - ((-48000) + i))) + i), 130))), safediv(i, a)) - (i & safediv(i, 1024)))) + shr(a, i))) & 0xFF;
}

// F44: percussive - Phaser Snare
// Infix: ((((66 >> ~t & t / 96) + b) / (t + (25 ^ t) % 1200 / 32768) & t) % (t & 133) & t | t / b) - t % (t % a)
static inline uint8_t formula_phaser_snare(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((((safemod((safediv(((shr(66, (~i)) & safediv(i, 96)) + b), (i + safediv(safemod((25 ^ i), 1200), 32768))) & i), (i & 133)) & i) | safediv(i, b)) - safemod(i, safemod(i, a)))) & 0xFF;
}

// F45: percussive - Percussive Beat
// Infix: ((105 >> -a) % t ^ b ^ (b | a * b % t ^ t)) + (56 | ~t) / 31
static inline uint8_t formula_percussive_beat(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((((safemod(shr(105, (-a)), i) ^ b) ^ (b | (safemod((a * b), i) ^ i))) + safediv((56 | (~i)), 31))) & 0xFF;
}

// F46: percussive - Seq Crash
// Infix: (t << (t | -2)) + 94 >> a | t % a | t ^ (16384 & (t & b) ^ ((~-32768 ^ a) % t & t + (b ^ -t)) % t - (1000 + 154))
static inline uint8_t formula_seq_crash(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((shr((shl(i, (i | (-2))) + 94), a) | safemod(i, a)) | (i ^ ((16384 & (i & b)) ^ (safemod((safemod(((~(-32768)) ^ a), i) & (i + (b ^ (-i)))), i) - (1000 + 154)))))) & 0xFF;
}

// F47: percussive - Phase Fall
// Infix: (t >> 128) % a * (218 * b ^ b / a) / t + t | (t & a) % (164 - (b | t)) & (37 | t)
static inline uint8_t formula_phase_fall(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((safediv((safemod(shr(i, 128), a) * ((218 * b) ^ safediv(b, a))), i) + i) | (safemod((i & a), (164 - (b | i))) & (37 | i)))) & 0xFF;
}

// F48: percussive - Glitch Splash
// Infix: b * ((a << 199) % (133 + b ^ t) - 512 ^ t) / t * b ^ t - t
static inline uint8_t formula_glitch_splash(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((safediv((b * ((safemod(shl(a, 199), ((133 + b) ^ i)) - 512) ^ i)), i) * b) ^ (i - i))) & 0xFF;
}

// F49: percussive - Hitting the Edge
// Infix: (t + ((b | a >> t * b) % b ^ b)) % 185 ^ (a << 71) % t ^ (-t >> 190) * b - (4096 | a) & t + t
static inline uint8_t formula_hitting_the_edge(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((safemod((i + (safemod((b | shr(a, (i * b))), b) ^ b)), 185) ^ safemod(shl(a, 71), i)) ^ (((shr((-i), 190) * b) - (4096 | a)) & (i + i)))) & 0xFF;
}

// F50: percussive - Dive Snare
// Infix: a ^ (a << 53) / (t + (t % (t % b) | b)) | t / b
static inline uint8_t formula_dive_snare(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((a ^ safediv(shl(a, 53), (i + (safemod(i, safemod(i, b)) | b)))) | safediv(i, b))) & 0xFF;
}

// F51: percussive - Energetic Hit
// Infix: b * a % ((32000 - b / (-127 * a)) % t ^ (24000 - b * (-a % 1200) + t) % t & (24000 - b * ~a + t) % t | t)
static inline uint8_t formula_energetic_hit(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(safemod((b * a), ((safemod((32000 - safediv(b, ((-127) * a))), i) ^ (safemod(((24000 - (b * safemod((-a), 1200))) + i), i) & safemod(((24000 - (b * (~a))) + i), i))) | i))) & 0xFF;
}

// F52: percussive - Noisy Drone Out
// Infix: 16000 % ~t ^ 8000 / (t / a - (600 + t) % b)
static inline uint8_t formula_noisy_drone_out(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safemod(16000, (~i)) ^ safediv(8000, (safediv(i, a) - safemod((600 + i), b))))) & 0xFF;
}

// F53: percussive - Ringmod Hit
// Infix: (24000 - b * (-a % 1200)) % (5000 % t ^ b / a & b + (24000 - b * (-a % (((b | a) >> 32768 % t) % t))))
static inline uint8_t formula_ringmod_hit(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(safemod((24000 - (b * safemod((-a), 1200))), (safemod(5000, i) ^ (safediv(b, a) & (b + (24000 - (b * safemod((-a), safemod(shr((b | a), safemod(32768, i)), i))))))))) & 0xFF;
}

// F54: percussive - Broken Crash Tone
// Infix: -((98 + a * -195) * (t % (-(102 % (300 + t) & t) | a) + t % (400 ^ b))) / t + a / ((95 | 70) / b & ~t)
static inline uint8_t formula_broken_crash_tone(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safediv((-((98 + (a * (-195))) * (safemod(i, ((-(safemod(102, (300 + i)) & i)) | a)) + safemod(i, (400 ^ b))))), i) + safediv(a, (safediv((95 | 70), b) & (~i))))) & 0xFF;
}

// F55: percussive - Angry Automaton
// Infix: (t ^ (b ^ (t ^ ((150 / -a | (t | t)) - (86 - 122) | ((-t ^ ~b) / -152 & 145 & t) / t) / (78 >> a) >> 10000 + t - t)) / a) * ((-76 & b * a) / -t) + ~t ^ t ^ 128
static inline uint8_t formula_angry_automaton(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((((((i ^ safediv((b ^ (i ^ shr(safediv((((safediv(150, (-a)) | (i | i)) - (86 - 122)) | safediv(((safediv(((-i) ^ (~b)), (-152)) & 145) & i), i)), shr(78, a)), ((10000 + i) - i)))), a)) * safediv(((-76) & (b * a)), (-i))) + (~i)) ^ i) ^ 128)) & 0xFF;
}

// F56: percussive - Cornflake Snare
// Infix: (t << ((t | t) << (t << (t >> b)) / a) / (188 * (~53 + 43)) << 141) / (t * t) + (223 ^ a)
static inline uint8_t formula_cornflake_snare(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safediv(shl(shl(i, safediv(shl((i | i), safediv(shl(i, shr(i, b)), a)), (188 * ((~53) + 43)))), 141), (i * i)) + (223 ^ a))) & 0xFF;
}

// F57: percussive - Crunch Into Drone
// Infix: (t % (a - (171 | ~b) - t % (-t % (t - t))) - 116 >> t & (t & 12000) - a ^ a + ~((t ^ -50) & t) ^ -(a - (23 >> ~b)) << 166) % t
static inline uint8_t formula_crunch_into_drone(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(safemod((((shr((safemod(i, ((a - (171 | (~b))) - safemod(i, safemod((-i), (i - i))))) - 116), i) & ((i & 12000) - a)) ^ (a + (~((i ^ (-50)) & i)))) ^ shl((-(a - shr(23, (~b)))), 166)), i)) & 0xFF;
}

// F58: percussive - Classic Pew Hit
// Infix: b * (87 * a + ~t) / t * 110
static inline uint8_t formula_classic_pew_hit(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safediv((b * ((87 * a) + (~i))), i) * 110)) & 0xFF;
}

// F59: percussive - Aliasing Hit
// Infix: b + 2000 % t * 127 ^ (a | b + a ^ b + 3000 % t * 102 + 44100 | b)
static inline uint8_t formula_aliasing_hit(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((b + (safemod(2000, i) * 127)) ^ ((a | ((b + a) ^ ((b + (safemod(3000, i) * 102)) + 44100))) | b))) & 0xFF;
}

// F60: rhythmic - High Freq Seq
// Infix: (t >> 165) % ((185 | t) & t / (a * (~t + t))) | (((a & t) + b ^ 512 | t) << (86 * t << b) | a & -((t | (~180 * t | t) / (b | t) % 97) + t) + 32768) >> (193 | t) % ~t
static inline uint8_t formula_high_freq_seq(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safemod(shr(i, 165), ((185 | i) & safediv(i, (a * ((~i) + i))))) | shr((shl(((((a & i) + b) ^ 512) | i), shl((86 * i), b)) | (a & ((-((i | safemod(safediv((((~180) * i) | i), (b | i)), 97)) + i)) + 32768))), safemod((193 | i), (~i))))) & 0xFF;
}

// F61: rhythmic - Hidden Melody
// Infix: (t - (((b | t) / a ^ (136 - -t) / -t * t) + t | (92 | 91))) % (t ^ (a / t >> 8000 | 184 << t)) ^ ~(b / (t * 19)) | t / 512
static inline uint8_t formula_hidden_melody(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((safemod((i - (((safediv((b | i), a) ^ (safediv((136 - (-i)), (-i)) * i)) + i) | (92 | 91))), (i ^ (shr(safediv(a, i), 8000) | shl(184, i)))) ^ (~safediv(b, (i * 19)))) | safediv(i, 512))) & 0xFF;
}

// F62: rhythmic - Marching Ants
// Infix: (b * t / a ^ ((((t * (214 - 117) + a) % b & ~t) - 122) * b / (31 + (a << t)) >> ((-a + -16384 ^ b ^ t) + 223) * b / t) + t + t) + t
static inline uint8_t formula_marching_ants(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((safediv((b * i), a) ^ ((shr(safediv((((safemod(((i * (214 - 117)) + a), b) & (~i)) - 122) * b), (31 + shl(a, i))), safediv(((((((-a) + (-16384)) ^ b) ^ i) + 223) * b), i)) + i) + i)) + i)) & 0xFF;
}

// F63: rhythmic - Blip Chopper
// Infix: (b * t / a ^ (t ^ -a) / -t + t) + t
static inline uint8_t formula_blip_chopper(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((safediv((b * i), a) ^ (safediv((i ^ (-a)), (-i)) + i)) + i)) & 0xFF;
}

// F64: rhythmic - Radio Chatter
// Infix: ((t >> (48000 | b) / 187 & (b - a / 3000 / t) % 1 - ((79 | b ^ 48000) & b * 133 / t << (22 ^ t / b + 4096) * a)) + (600 * (28 + 162 - b) - ~a | (222 | t) << a ^ 39)) % ~a
static inline uint8_t formula_radio_chatter(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(safemod(((shr(i, safediv((48000 | b), 187)) & (safemod((b - safediv(safediv(a, 3000), i)), 1) - ((79 | (b ^ 48000)) & shl(safediv((b * 133), i), ((22 ^ (safediv(i, b) + 4096)) * a))))) + (((600 * ((28 + 162) - b)) - (~a)) | (shl((222 | i), a) ^ 39))), (~a))) & 0xFF;
}

// F65: rhythmic - Phasing Bassline
// Infix: t & ((t - b) % t / (32 & 1000) ^ (a | (b & t) >> a >> t) + t) ^ -~t
static inline uint8_t formula_phasing_bassline(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((i & (safediv(safemod((i - b), i), (32 & 1000)) ^ ((a | shr(shr((b & i), a), i)) + i))) ^ (-(~i)))) & 0xFF;
}

// F66: rhythmic - IDM Beat
// Infix: ~((b + t - (a % (46 * (t * t) & t - b) >> (b - 70 / 54) % a % t / (t * 300))) / 35) ^ t | t & 87 / (b | t)
static inline uint8_t formula_idm_beat(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((((~safediv(((b + i) - shr(safemod(a, ((46 * (i * i)) & (i - b))), safediv(safemod(safemod((b - safediv(70, 54)), a), i), (i * 300)))), 35)) ^ i) | (i & safediv(87, (b | i))))) & 0xFF;
}

// F67: rhythmic - Chaos Arping
// Infix: (b + t / ((38 & a | (t << t) * 3 & (t - t & t) * (t * (t >> (-t ^ t) << t) & t)) >> 30 / b) ^ t) % t
static inline uint8_t formula_chaos_arping(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(safemod(((b + safediv(i, shr(((38 & a) | ((shl(i, i) * 3) & (((i - i) & i) * ((i * shl(shr(i, ((-i) ^ i)), i)) & i)))), safediv(30, b)))) ^ i), i)) & 0xFF;
}

// F68: rhythmic - Glitch Bass
// Infix: -(t % ~b - a) ^ t - t / (-(43 * (t >> 206 >> b) - t) >> (44100 ^ b) - t >> t) >> (t / 56 ^ a >> t >> ~(77 - t))
static inline uint8_t formula_glitch_bass(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((-(safemod(i, (~b)) - a)) ^ shr((i - safediv(i, shr(shr((-((43 * shr(shr(i, 206), b)) - i)), ((44100 ^ b) - i)), i))), (safediv(i, 56) ^ shr(shr(a, i), (~(77 - i))))))) & 0xFF;
}

// F69: rhythmic - Pulsing Gnat
// Infix: (~t - t & (68 | a - t % 194) >> (25 >> 205) >> 218) - (t >> ((t - ~~12) % 16384 | t) * 51) >> t ^ b
static inline uint8_t formula_pulsing_gnat(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((shr(((((~i) - i) & shr(shr((68 | (a - safemod(i, 194))), shr(25, 205)), 218)) - shr(i, ((safemod((i - (~(~12))), 16384) | i) * 51))), i) ^ b)) & 0xFF;
}

// F70: rhythmic - 8 Bar Glitch Sync
// Infix: (t >> (16000 % (b * (t | ~-5000)) ^ (8000 >> (a >> t) | b / ((a | t) >> 109 * 171)))) - b % ((a ^ t) & t * 77)
static inline uint8_t formula_f_8_bar_glitch_sync(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((shr(i, (safemod(16000, (b * (i | (~(-5000))))) ^ (shr(8000, shr(a, i)) | safediv(b, shr((a | i), (109 * 171)))))) - safemod(b, ((a ^ i) & (i * 77))))) & 0xFF;
}

// F71: rhythmic - Scratch Throb
// Infix: ((2500 ^ a >> ~-t) + t) % (t - (((t ^ 1024) * a | t / 49) - (16000 + (t ^ t)) + b % (60 / ((140 / (a >> 144 - t) << a % t) + 176)) % (b << 195) | ((-t ^ 1200) + t) / b))
static inline uint8_t formula_scratch_throb(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(safemod(((2500 ^ shr(a, (~(-i)))) + i), (i - ((((((i ^ 1024) * a) | safediv(i, 49)) - (16000 + (i ^ i))) + safemod(safemod(b, safediv(60, (shl(safediv(140, shr(a, (144 - i))), safemod(a, i)) + 176))), shl(b, 195))) | safediv((((-i) ^ 1200) + i), b))))) & 0xFF;
}

// F72: rhythmic - Grain Period
// Infix: ((((t*t>>(6+(a>>6)))&255))>>((t%(600+(b<<3)))>>8))
static inline uint8_t formula_grain_period(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(shr((shr((i * i), (6 + shr(a, 6))) & 255), shr(safemod(i, (600 + shl(b, 3))), 8))) & 0xFF;
}

// F73: rhythmic - Cycling Hits
// Infix: ((85 ^ 109 >> 188) % (t - (b ^ a)) * a % b | ((~t | ~t / a) ^ t) << (t | t >> 12000) << b) - (t + (48000 >> (t >> (t / a >> (b >> 50 & b)))))
static inline uint8_t formula_cycling_hits(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((safemod((safemod((85 ^ shr(109, 188)), (i - (b ^ a))) * a), b) | shl(shl((((~i) | safediv((~i), a)) ^ i), (i | shr(i, 12000))), b)) - (i + shr(48000, shr(i, shr(safediv(i, a), (shr(b, 50) & b))))))) & 0xFF;
}

// F74: rhythmic - Emergency
// Infix: t / b | a * ~t | a * b + t - a << 13
static inline uint8_t formula_emergency(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((safediv(i, b) | (a * (~i))) | shl((((a * b) + i) - a), 13))) & 0xFF;
}

// F75: rhythmic - Crash and Beat
// Infix: (t - ((32768 % t - ((t - (~t >> b)) * 33 ^ (38 - 40 | (-t + (~t + a) ^ t) % t))) / (t >> (196 ^ t >> a)) + 97) | t) - (10000 % t - t + 159 | t ^ t) + ((b | (t | t) % a) ^ t)
static inline uint8_t formula_crash_and_beat(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((((i - (safediv((safemod(32768, i) - (((i - shr((~i), b)) * 33) ^ ((38 - 40) | safemod((((-i) + ((~i) + a)) ^ i), i)))), shr(i, (196 ^ shr(i, a)))) + 97)) | i) - (((safemod(10000, i) - i) + 159) | (i ^ i))) + ((b | safemod((i | i), a)) ^ i))) & 0xFF;
}

// F76: rhythmic - Four on the Glitch
// Infix: (((t + t) % t << a) << 38) / 143 - (t + (b ^ (t ^ t / (~t / (-(a - (~t + t - t)) | t)))))
static inline uint8_t formula_four_on_the_glitch(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safediv(shl(shl(safemod((i + i), i), a), 38), 143) - (i + (b ^ (i ^ safediv(i, safediv((~i), ((-(a - (((~i) + i) - i))) | i)))))))) & 0xFF;
}

// F77: rhythmic - Elemental Loop
// Infix: (t ^ t * b) / a | t / b
static inline uint8_t formula_elemental_loop(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safediv((i ^ (i * b)), a) | safediv(i, b))) & 0xFF;
}

// F78: rhythmic - Electro Chatter
// Infix: (t >> ~186) + (t | b) << ((t >> a << t) * ((10000 + t) / (179 / t - 91)) / t % t & (b & t)) ^ 300 % ((t & a & (t ^ 132)) >> t * 148 + t)
static inline uint8_t formula_electro_chatter(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((shl((shr(i, (~186)) + (i | b)), (safemod(safediv((shl(shr(i, a), i) * safediv((10000 + i), (safediv(179, i) - 91))), i), i) & (b & i))) ^ safemod(300, shr(((i & a) & (i ^ 132)), ((i * 148) + i))))) & 0xFF;
}

// F79: rhythmic - Algorunning
// Infix: 181 & (t ^ a * (b & t / 200) - ((t ^ t) & 8192) ^ t * ~~(-76 + a)) | (185 * (2000 >> -204 & t) | (b + t) / b)
static inline uint8_t formula_algorunning(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((181 & ((i ^ ((a * (b & safediv(i, 200))) - ((i ^ i) & 8192))) ^ (i * (~(~((-76) + a)))))) | ((185 * (shr(2000, (-204)) & i)) | safediv((b + i), b)))) & 0xFF;
}

// F80: melodic - Melody Rhythm Pump
// Infix: 3 + t - (t / a ^ t) ^ b
static inline uint8_t formula_melody_rhythm_pump(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((((3 + i) - (safediv(i, a) ^ i)) ^ b)) & 0xFF;
}

// F81: melodic - Melodic Riser
// Infix: ~((a - (b << t | (~b ^ ~102 * t) * t % ((14 + a) % (-b * (~t % t) - t | t / 3)))) / 115)
static inline uint8_t formula_melodic_riser(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((~safediv((a - (shl(b, i) | safemod((((~b) ^ ((~102) * i)) * i), safemod((14 + a), ((((-b) * safemod((~i), i)) - i) | safediv(i, 3)))))), 115))) & 0xFF;
}

// F82: melodic - Blip Sequence
// Infix: ((b | t) / a ^ ((t / b | a) & 115 & ((~-(50 ^ t) + 114) / t / -179 + t - ((t % (~(t * t) + t) ^ t) & t)) % (t ^ -(a % t % b)) | t ^ b & 98)) + t
static inline uint8_t formula_blip_sequence(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((safediv((b | i), a) ^ ((((safediv(i, b) | a) & 115) & safemod(((safediv(safediv(((~(-(50 ^ i))) + 114), i), (-179)) + i) - ((safemod(i, ((~(i * i)) + i)) ^ i) & i)), (i ^ (-safemod(safemod(a, i), b))))) | (i ^ (b & 98)))) + i)) & 0xFF;
}

// F83: melodic - Phasing Drone
// Infix: (t + (t + t)) % ((10 | t) / a ^ t % ~(a - (b | (t * t | t)) | ~(b * 79)) / t << -(b % (t * t)) >> 4096) + ~b
static inline uint8_t formula_phasing_drone(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safemod((i + (i + i)), (safediv((10 | i), a) ^ shr(shl(safediv(safemod(i, (~((a - (b | ((i * i) | i))) | (~(b * 79))))), i), (-safemod(b, (i * i)))), 4096))) + (~b))) & 0xFF;
}

// F84: melodic - Melody Drone Beat
// Infix: a % t >> (t << (b - t) / (76 % 85)) ^ (t - (b ^ t) ^ t >> t / b) >> t
static inline uint8_t formula_melody_drone_beat(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((shr(safemod(a, i), shl(i, safediv((b - i), safemod(76, 85)))) ^ shr(((i - (b ^ i)) ^ shr(i, safediv(i, b))), i))) & 0xFF;
}

// F85: melodic - Gently Evolving
// Infix: -(t % -b - a) & ~t + (b / (((t + 111) / t | (214 ^ 160) / (a << t) % 85) % t | 112 & 32768 % (19 >> a)) ^ (t + (a | b) % a) % t) - (127 | 8192) >> (t << ~b) - a
static inline uint8_t formula_gently_evolving(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((-(safemod(i, (-b)) - a)) & shr((((~i) + (safediv(b, (safemod((safediv((i + 111), i) | safemod(safediv((214 ^ 160), shl(a, i)), 85)), i) | (112 & safemod(32768, shr(19, a))))) ^ safemod((i + safemod((a | b), a)), i))) - (127 | 8192)), (shl(i, (~b)) - a)))) & 0xFF;
}

// F86: melodic - Ring Swing
// Infix: ((((t*(4+(a>>6)))*(t>>9))&255))>>((t%(450+(b<<3)))>>8)
static inline uint8_t formula_ring_swing(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(shr((((i * (4 + shr(a, 6))) * shr(i, 9)) & 255), shr(safemod(i, (450 + shl(b, 3))), 8))) & 0xFF;
}

// F87: melodic - Sub Harmony Chop
// Infix: ((((t*2)&255)>>1)+(((t*(4+(a>>5)))&255)>>2))>>((t&(1023+(b<<4)))>>9)
static inline uint8_t formula_sub_harmony_chop(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(shr((shr(((i * 2) & 255), 1) + shr(((i * (4 + shr(a, 5))) & 255), 2)), shr((i & (1023 + shl(b, 4))), 9))) & 0xFF;
}

// F88: melodic - Melodic to Noise
// Infix: ((((b ^ t / a) - 132) % 181 | (a & ((t * t ^ t) % t | t % (b ^ -t)) + 3000) >> b / (~-32768 << a << t | a % (b ^ ~t))) ^ t) + t
static inline uint8_t formula_melodic_to_noise(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((((safemod(((b ^ safediv(i, a)) - 132), 181) | shr((a & ((safemod(((i * i) ^ i), i) | safemod(i, (b ^ (-i)))) + 3000)), safediv(b, (shl(shl((~(-32768)), a), i) | safemod(a, (b ^ (~i))))))) ^ i) + i)) & 0xFF;
}

// F89: melodic - Held Note Glitch
// Infix: a * 4096 * b / ((t | t << t) - (a << 400)) + ((t & t) >> (t ^ -25 % (t & t)) % t)
static inline uint8_t formula_held_note_glitch(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safediv(((a * 4096) * b), ((i | shl(i, i)) - shl(a, 400))) + shr((i & i), safemod((i ^ safemod((-25), (i & i))), i)))) & 0xFF;
}

// F90: melodic - Gentle Arpeggio
// Infix: (t / a | t + ((t / ~b ^ t) << a)) + (b ^ t)
static inline uint8_t formula_gentle_arpeggio(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((safediv(i, a) | (i + shl((safediv(i, (~b)) ^ i), a))) + (b ^ i))) & 0xFF;
}

// F91: melodic - Sing Song
// Infix: 96 + b ^ (t | (t / ~a | t & ~166 << b)) + (-t - (t ^ a)) ^ (t % -a ^ t) >> (a << 204) / b & a - 1200
static inline uint8_t formula_sing_song(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((((96 + b) ^ ((i | (safediv(i, (~a)) | (i & shl((~166), b)))) + ((-i) - (i ^ a)))) ^ (shr((safemod(i, (-a)) ^ i), safediv(shl(a, 204), b)) & (a - 1200)))) & 0xFF;
}

// F92: melodic - Glitchy Song
// Infix: ((-63 << 85 & a) << 38) / 143 - (t + (b ^ (t ^ t / (~t / (-(1024 - (~t + t - t)) | t)))))
static inline uint8_t formula_glitchy_song(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((safediv(shl((shl((-63), 85) & a), 38), 143) - (i + (b ^ (i ^ safediv(i, safediv((~i), ((-(1024 - (((~i) + i) - i))) | i)))))))) & 0xFF;
}

// F93: melodic - Classic Byte Arp
// Infix: t / a | t ^ (1000 * b | t % t ^ 154) + (t * b ^ t) | t / b
static inline uint8_t formula_classic_byte_arp(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((safediv(i, a) | (i ^ (((1000 * b) | (safemod(i, i) ^ 154)) + ((i * b) ^ i)))) | safediv(i, b))) & 0xFF;
}

// F94: melodic - Pulsing Line
// Infix: ((t & a) - t / b >> (b << a & (a + 62 << t) % t % t)) % t % t
static inline uint8_t formula_pulsing_line(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(safemod(safemod(shr(((i & a) - safediv(i, b)), (shl(b, a) & safemod(safemod(shl((a + 62), i), i), i))), i), i)) & 0xFF;
}

// F95: melodic - Hidden Paths
// Infix: (44100 + a * ~195) * (t % (6000 + 1000 - t >> ~b) + 75 % (20 / b))
static inline uint8_t formula_hidden_paths(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((44100 + (a * (~195))) * (safemod(i, shr(((6000 + 1000) - i), (~b))) + safemod(75, safediv(20, b))))) & 0xFF;
}

// F96: melodic - Melody Gate
// Infix: (t / t + 114) * ((-42 & b * a) / -t) + ~t ^ t ^ 128
static inline uint8_t formula_melody_gate(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((((((safediv(i, i) + 114) * safediv(((-42) & (b * a)), (-i))) + (~i)) ^ i) ^ 128)) & 0xFF;
}

// F97: melodic - Simple Arp Notes
// Infix: (t ^ b) - -t % (a << 133 ^ t) % (t + b | a >> (16384 * 191 | 118 * b) ^ (t - b | (62 & (8000 ^ b & t ^ 62) | b)))
static inline uint8_t formula_simple_arp_notes(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)(((i ^ b) - safemod(safemod((-i), (shl(a, 133) ^ i)), ((i + b) | (shr(a, ((16384 * 191) | (118 * b))) ^ ((i - b) | ((62 & ((8000 ^ (b & i)) ^ 62)) | b))))))) & 0xFF;
}

// F98: melodic - Broken Song
// Infix: a - (t ^ (t - 1) / -b) ^ 2500 % t << 118 ^ (t | b)
static inline uint8_t formula_broken_song(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((((a - (i ^ safediv((i - 1), (-b)))) ^ shl(safemod(2500, i), 118)) ^ (i | b))) & 0xFF;
}

// F99: melodic - Oldskool Tune
// Infix: (t % b - (~b / 1200 - 21) | t / a) - b
static inline uint8_t formula_oldskool_tune(uint32_t t, int32_t a, int32_t b) {
    int32_t i = (int32_t)t;
    return (uint8_t)((((safemod(i, b) - (safediv((~b), 1200) - 21)) | safediv(i, a)) - b)) & 0xFF;
}

// --- not part of the numbered bank ---

// A440 tuning reference (daisy-vu3). Triangle wave; ignores A/B. Clocked at
// its base rate (28160 Hz) at 1x, one cycle = 64 t-samples -> 28160/64 = 440.0 Hz
// exactly. The engine forces rate=1x while this is Out1's formula, so the pitch is
// independent of the Rate knob / clock / V-oct. Displayed as function "AA".
static inline uint8_t formula_ref_a440(uint32_t t, int32_t /*a*/, int32_t /*b*/) {
    uint32_t p = (t * 4u) & 0xFFu;                              // sawtooth, period 64
    return (uint8_t)(p < 128u ? (p * 2u) : ((255u - p) * 2u));  // fold to a triangle
}

// Formula access. There are 100 numbered slots (0..99) plus a special A440
// reference slot (index 100, displayed "AA"); GetFormulaCount() = 101. All
// hundred numbered slots are filled; an out-of-range index returns slot 0.
const FormulaInfo* GetFormulaAt(int index);  // safe for 0..GetFormulaCount()-1
int GetFormulaCount();
int GetReferenceIndex();          // index of the A440 reference (the "AA" slot)
int GetNumberedSlotCount();       // count of numbered slots (100)
