// -----------------------------------------------------------------------------
// Ogham — a dual-voice bytebeat synthesizer for Eurorack
//
// Author:     Steven Collins, 2026, Keeos.io
// Copyright:  (c) 2026 Steven Collins
//
// SPDX-FileCopyrightText: 2026 Steven Collins <https://keeos.io>
// SPDX-License-Identifier: MIT
//
// This file is part of the Ogham firmware. See LICENSE-firmware.txt at the
// repository root for the full licence text.
// https://github.com/keeos-io/ogham
// -----------------------------------------------------------------------------

#include "formulas.h"

// GENERATED by bytebeat/tools/gen_ogham_bank.cpp from the curated library.
// Do not hand-edit.
//
// The hundred curated formulas, twenty of each type, in the order the
// numbering implies: textural 0-19, noise 20-39, percussive 40-59,
// rhythmic 60-79, melodic 80-99.

static const FormulaInfo formulaTable[] = {
    // ---- textural (0-19) ----
    {
        "Electric Drone",
        "stevec64",
        formula_electric_drone,
        8000,
    },  // F00
    {
        "Lofi Drone",
        "stevec64",
        formula_lofi_drone,
        8000,
    },  // F01
    {
        "Disolving Beat",
        "stevec64",
        formula_disolving_beat,
        8000,
    },  // F02
    {
        "Sweep to Drone",
        "stevec64",
        formula_sweep_to_drone,
        8000,
    },  // F03
    {
        "Sweep to Crunch",
        "stevec64",
        formula_sweep_to_crunch,
        8000,
    },  // F04
    {
        "Noisy Alarm",
        "stevec64",
        formula_noisy_alarm,
        8000,
    },  // F05
    {
        "Rise of the Glitch",
        "stevec64",
        formula_rise_of_the_glitch,
        8000,
    },  // F06
    {
        "Robotic Drone",
        "stevec64",
        formula_robotic_drone,
        8000,
    },  // F07
    {
        "Bitty Drone",
        "stevec64",
        formula_bitty_drone,
        8000,
    },  // F08
    {
        "Texture Sequence",
        "stevec64",
        formula_texture_sequence,
        8000,
    },  // F09
    {
        "Noise to Drone",
        "stevec64",
        formula_noise_to_drone,
        8000,
    },  // F10
    {
        "Falling Down",
        "stevec64",
        formula_falling_down,
        8000,
    },  // F11
    {
        "Power Drone",
        "stevec64",
        formula_power_drone,
        8000,
    },  // F12
    {
        "Run Away",
        "stevec64",
        formula_run_away,
        8000,
    },  // F13
    {
        "Slowly Rising",
        "stevec64",
        formula_slowly_rising,
        8000,
    },  // F14
    {
        "Failing Electro Loop",
        "stevec64",
        formula_failing_electro_loop,
        8000,
    },  // F15
    {
        "Ring Descent",
        "stevec64",
        formula_ring_descent,
        8000,
    },  // F16
    {
        "Changing Times",
        "stevec64",
        formula_changing_times,
        8000,
    },  // F17
    {
        "Scanner",
        "stevec64",
        formula_scanner,
        8000,
    },  // F18
    {
        "Texture from Tone",
        "stevec64",
        formula_texture_from_tone,
        8000,
    },  // F19

    // ---- noise (20-39) ----
    {
        "Crunch Pulse",
        "stevec64",
        formula_crunch_pulse,
        8000,
    },  // F20
    {
        "Electronic Beating",
        "stevec64",
        formula_electronic_beating,
        8000,
    },  // F21
    {
        "Fluttery",
        "stevec64",
        formula_fluttery,
        8000,
    },  // F22
    {
        "Circuit Bent",
        "stevec64",
        formula_circuit_bent,
        8000,
    },  // F23
    {
        "Where is my Filter",
        "stevec64",
        formula_where_is_my_filter,
        8000,
    },  // F24
    {
        "Decent Into Chaos",
        "stevec64",
        formula_decent_into_chaos,
        8000,
    },  // F25
    {
        "Pulsing static",
        "stevec64",
        formula_pulsing_static,
        8000,
    },  // F26
    {
        "Hunt The Wumpus",
        "stevec64",
        formula_hunt_the_wumpus,
        8000,
    },  // F27
    {
        "Harmonic Noise Seq",
        "stevec64",
        formula_harmonic_noise_seq,
        8000,
    },  // F28
    {
        "Gritty Drone",
        "stevec64",
        formula_gritty_drone,
        8000,
    },  // F29
    {
        "Red Noise",
        "stevec64",
        formula_red_noise,
        8000,
    },  // F30
    {
        "Evolution of Noise",
        "stevec64",
        formula_evolution_of_noise,
        8000,
    },  // F31
    {
        "Riser Noise",
        "stevec64",
        formula_riser_noise,
        8000,
    },  // F32
    {
        "Fluttering Grind",
        "stevec64",
        formula_fluttering_grind,
        8000,
    },  // F33
    {
        "Frying Pan",
        "stevec64",
        formula_frying_pan,
        8000,
    },  // F34
    {
        "Destructive Riser",
        "stevec64",
        formula_destructive_riser,
        8000,
    },  // F35
    {
        "Oblivion",
        "stevec64",
        formula_oblivion,
        8000,
    },  // F36
    {
        "Jet Phase",
        "stevec64",
        formula_jet_phase,
        8000,
    },  // F37
    {
        "Broken Morse",
        "stevec64",
        formula_broken_morse,
        8000,
    },  // F38
    {
        "Grunge Gate",
        "stevec64",
        formula_grunge_gate,
        8000,
    },  // F39

    // ---- percussive (40-59) ----
    {
        "Recursive Descent",
        "stevec64",
        formula_recursive_descent,
        8000,
    },  // F40
    {
        "V8 Fall",
        "stevec64",
        formula_v8_fall,
        8000,
    },  // F41
    {
        "Crash Breakdown",
        "stevec64",
        formula_crash_breakdown,
        8000,
    },  // F42
    {
        "Decent to Melody",
        "stevec64",
        formula_decent_to_melody,
        8000,
    },  // F43
    {
        "Phaser Snare",
        "stevec64",
        formula_phaser_snare,
        8000,
    },  // F44
    {
        "Percussive Beat",
        "stevec64",
        formula_percussive_beat,
        8000,
    },  // F45
    {
        "Seq Crash",
        "stevec64",
        formula_seq_crash,
        8000,
    },  // F46
    {
        "Phase Fall",
        "stevec64",
        formula_phase_fall,
        8000,
    },  // F47
    {
        "Glitch Splash",
        "stevec64",
        formula_glitch_splash,
        8000,
    },  // F48
    {
        "Hitting the Edge",
        "stevec64",
        formula_hitting_the_edge,
        8000,
    },  // F49
    {
        "Dive Snare",
        "stevec64",
        formula_dive_snare,
        8000,
    },  // F50
    {
        "Energetic Hit",
        "stevec64",
        formula_energetic_hit,
        8000,
    },  // F51
    {
        "Noisy Drone Out",
        "stevec64",
        formula_noisy_drone_out,
        8000,
    },  // F52
    {
        "Ringmod Hit",
        "stevec64",
        formula_ringmod_hit,
        8000,
    },  // F53
    {
        "Broken Crash Tone",
        "stevec64",
        formula_broken_crash_tone,
        8000,
    },  // F54
    {
        "Angry Automaton",
        "stevec64",
        formula_angry_automaton,
        8000,
    },  // F55
    {
        "Cornflake Snare",
        "stevec64",
        formula_cornflake_snare,
        8000,
    },  // F56
    {
        "Crunch Into Drone",
        "stevec64",
        formula_crunch_into_drone,
        8000,
    },  // F57
    {
        "Classic Pew Hit",
        "stevec64",
        formula_classic_pew_hit,
        8000,
    },  // F58
    {
        "Aliasing Hit",
        "stevec64",
        formula_aliasing_hit,
        8000,
    },  // F59

    // ---- rhythmic (60-79) ----
    {
        "High Freq Seq",
        "stevec64",
        formula_high_freq_seq,
        8000,
    },  // F60
    {
        "Hidden Melody",
        "stevec64",
        formula_hidden_melody,
        8000,
    },  // F61
    {
        "Marching Ants",
        "stevec64",
        formula_marching_ants,
        8000,
    },  // F62
    {
        "Blip Chopper",
        "stevec64",
        formula_blip_chopper,
        8000,
    },  // F63
    {
        "Radio Chatter",
        "stevec64",
        formula_radio_chatter,
        8000,
    },  // F64
    {
        "Phasing Bassline",
        "stevec64",
        formula_phasing_bassline,
        8000,
    },  // F65
    {
        "IDM Beat",
        "stevec64",
        formula_idm_beat,
        8000,
    },  // F66
    {
        "Chaos Arping",
        "stevec64",
        formula_chaos_arping,
        8000,
    },  // F67
    {
        "Glitch Bass",
        "stevec64",
        formula_glitch_bass,
        8000,
    },  // F68
    {
        "Pulsing Gnat",
        "stevec64",
        formula_pulsing_gnat,
        8000,
    },  // F69
    {
        "8 Bar Glitch Sync",
        "stevec64",
        formula_f_8_bar_glitch_sync,
        8000,
    },  // F70
    {
        "Scratch Throb",
        "stevec64",
        formula_scratch_throb,
        8000,
    },  // F71
    {
        "Grain Period",
        "stevec64",
        formula_grain_period,
        8000,
    },  // F72
    {
        "Cycling Hits",
        "stevec64",
        formula_cycling_hits,
        8000,
    },  // F73
    {
        "Emergency",
        "stevec64",
        formula_emergency,
        8000,
    },  // F74
    {
        "Crash and Beat",
        "stevec64",
        formula_crash_and_beat,
        8000,
    },  // F75
    {
        "Four on the Glitch",
        "stevec64",
        formula_four_on_the_glitch,
        8000,
    },  // F76
    {
        "Elemental Loop",
        "stevec64",
        formula_elemental_loop,
        8000,
    },  // F77
    {
        "Electro Chatter",
        "stevec64",
        formula_electro_chatter,
        8000,
    },  // F78
    {
        "Algorunning",
        "stevec64",
        formula_algorunning,
        8000,
    },  // F79

    // ---- melodic (80-99) ----
    {
        "Melody Rhythm Pump",
        "stevec64",
        formula_melody_rhythm_pump,
        8000,
    },  // F80
    {
        "Melodic Riser",
        "stevec64",
        formula_melodic_riser,
        8000,
    },  // F81
    {
        "Blip Sequence",
        "stevec64",
        formula_blip_sequence,
        8000,
    },  // F82
    {
        "Phasing Drone",
        "stevec64",
        formula_phasing_drone,
        8000,
    },  // F83
    {
        "Melody Drone Beat",
        "stevec64",
        formula_melody_drone_beat,
        8000,
    },  // F84
    {
        "Gently Evolving",
        "stevec64",
        formula_gently_evolving,
        8000,
    },  // F85
    {
        "Ring Swing",
        "stevec64",
        formula_ring_swing,
        8000,
    },  // F86
    {
        "Sub Harmony Chop",
        "stevec64",
        formula_sub_harmony_chop,
        8000,
    },  // F87
    {
        "Melodic to Noise",
        "stevec64",
        formula_melodic_to_noise,
        8000,
    },  // F88
    {
        "Held Note Glitch",
        "stevec64",
        formula_held_note_glitch,
        8000,
    },  // F89
    {
        "Gentle Arpeggio",
        "stevec64",
        formula_gentle_arpeggio,
        8000,
    },  // F90
    {
        "Sing Song",
        "stevec64",
        formula_sing_song,
        8000,
    },  // F91
    {
        "Glitchy Song",
        "stevec64",
        formula_glitchy_song,
        8000,
    },  // F92
    {
        "Classic Byte Arp",
        "stevec64",
        formula_classic_byte_arp,
        8000,
    },  // F93
    {
        "Pulsing Line",
        "stevec64",
        formula_pulsing_line,
        8000,
    },  // F94
    {
        "Hidden Paths",
        "stevec64",
        formula_hidden_paths,
        8000,
    },  // F95
    {
        "Melody Gate",
        "stevec64",
        formula_melody_gate,
        8000,
    },  // F96
    {
        "Simple Arp Notes",
        "stevec64",
        formula_simple_arp_notes,
        8000,
    },  // F97
    {
        "Broken Song",
        "stevec64",
        formula_broken_song,
        8000,
    },  // F98
    {
        "Oldskool Tune",
        "stevec64",
        formula_oldskool_tune,
        8000,
    },  // F99
};

// Number of authored (real) formulas at the front of the numbered range.
static const int NUM_REAL = sizeof(formulaTable) / sizeof(formulaTable[0]);

// 100 numbered slots (0..99), all of them filled.
static constexpr int NUM_NUMBERED = 100;

// Special A440 tuning reference -- the "AA" slot (index 100, past the numbers).
static const FormulaInfo kRefA440Slot = {
    "ref A440", "keeos", formula_ref_a440,
    28154,      // tuned on hardware to read A=440.0Hz (28096 -> 439.1Hz; freq scales
                // linearly with base; corrects the real codec rate vs assumed 48kHz)
};

int GetFormulaCount()      { return NUM_NUMBERED + 1; }  // 100 numbered + AA
int GetReferenceIndex()    { return NUM_NUMBERED; }      // index 100 = "AA"
int GetNumberedSlotCount() { return NUM_NUMBERED; }

const FormulaInfo* GetFormulaAt(int index) {
    if (index == NUM_NUMBERED) return &kRefA440Slot;          // "AA" reference
    if (index >= 0 && index < NUM_REAL) return &formulaTable[index];
    return &formulaTable[0];                                  // out of range
}
